import 'dart:io';
import 'dart:math';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:path_provider/path_provider.dart';
import '../models/evidence.dart';

import 'dart:convert';
import 'package:crypto/crypto.dart';

/// Result of generating a GD dossier: the exported PDF plus the metadata
/// needed to persist a [Complaint] record.
class GeneratedComplaint {
  final String pdfPath;
  final String dossierId;
  final String generatedText;
  final String masterHash;

  GeneratedComplaint({
    required this.pdfPath,
    required this.dossierId,
    required this.generatedText,
    required this.masterHash,
  });
}

class GenerateComplaintUseCase {
  /// Dossier IDs must match the schema in
  /// `legal/e_gd_schema_mapping.md`: `^PROTITI-[A-Z0-9]{8}-[0-9]{4}$`.
  static String _generateDossierId() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    final rand = Random.secure();
    final code = List.generate(8, (_) => chars[rand.nextInt(chars.length)]).join();
    final seq = (1000 + rand.nextInt(9000)).toString();
    return 'PROTITI-$code-$seq';
  }

  Future<GeneratedComplaint> execute(
    List<Evidence> evidence,
    Map<String, dynamic> answers,
  ) async {
    final pdf = pw.Document();

    final dossierId = _generateDossierId();
    // Standard cyber complaints route straight to the e-GD portal path;
    // PCSW/999/CID routing needs the severity intake this wizard doesn't
    // collect yet, so it isn't claimed here.
    const triageRoute = 'EGD_DIRECT';

    final title = answers['title'] ?? 'General Diary Complaint';
    final description = answers['description'] ?? 'No description provided.';
    final policeStation = answers['station'] ?? 'Officer-in-Charge';
    final timestamp = DateTime.now().toIso8601String();

    // Generate SHA-256 hash for evidence
    List<Map<String, String>> hashedEvidence = [];
    for (var e in evidence) {
      final input = '${e.id}_${e.type}_${e.description}';
      final hash = sha256.convert(utf8.encode(input)).toString();
      hashedEvidence.add({
        'type': e.type,
        'description': e.description,
        'hash': hash,
      });
    }

    // Generate a master verification hash
    final masterInput =
        '$dossierId|$title|$description|$policeStation|$timestamp|${hashedEvidence.map((e) => e['hash']).join(',')}';
    final masterHash = sha256.convert(utf8.encode(masterInput)).toString();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text(
                'Formal General Diary (GD) Complaint',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.Text(
              'Dossier ID: $dossierId',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 12),
            ),
            pw.SizedBox(height: 12),
            pw.Container(
              padding: const pw.EdgeInsets.all(8),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey700),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
              ),
              child: pw.Text(
                'This is an offline, schema-compliant digital dossier generated by Protiti for manual submission. '
                'Bangladesh Police do not offer a public API for direct GD submission from third-party apps — this '
                'document has NOT been transmitted to gd.police.gov.bd or any government system. Present this PDF '
                '(printed or digital) to the Duty Officer at the relevant Thana, or forward it to the Police Cyber '
                'Support for Women (PCSW) helpline at 01320000888 / pcsw@police.gov.bd for priority escalation.',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey800),
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Text('To: The Officer-in-Charge, $policeStation'),
            pw.SizedBox(height: 8),
            pw.Text(
              'Subject: $title',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 16),
            pw.Text('Dear Sir/Madam,'),
            pw.SizedBox(height: 8),
            pw.Text(
              'I, the undersigned, hereby report the following incident:',
            ),
            pw.SizedBox(height: 12),
            pw.Paragraph(text: description),
            pw.SizedBox(height: 20),
            pw.Text(
              'EVIDENCE ATTACHED (Cryptographically Hashed):',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16),
            ),
            pw.SizedBox(height: 10),
            if (hashedEvidence.isEmpty) pw.Text('No evidence attached.'),
            ...hashedEvidence
                .map(
                  (e) => pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 8),
                    child: pw.Bullet(
                      text:
                          'Type: ${e['type']?.toUpperCase()} | Desc: ${e['description']}\nSHA-256: ${e['hash']}',
                    ),
                  ),
                ),
            pw.SizedBox(height: 30),
            pw.Center(
              child: pw.Column(
                children: [
                  pw.BarcodeWidget(
                    data: masterHash,
                    barcode: pw.Barcode.qrCode(),
                    width: 100,
                    height: 100,
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    'Scan to verify digital integrity',
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 30),
            pw.Text(
              'Generated securely via Protiti Forensic Vault',
              style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10),
            ),
            pw.Text(
              'Timestamp: $timestamp',
              style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10),
            ),
            pw.Text(
              'Triage Route: $triageRoute',
              style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10),
            ),
            pw.Text(
              'Verification Hash: $masterHash',
              style: const pw.TextStyle(color: PdfColors.grey, fontSize: 8),
            ),
          ];
        },
      ),
    );

    final tempDir = await getTemporaryDirectory();
    final file = File(
      '${tempDir.path}/GD_Complaint_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
    await file.writeAsBytes(await pdf.save());

    final generatedText =
        'To: $policeStation\nSubject: $title\n\n$description\n\nEvidence attached: ${hashedEvidence.length}';

    return GeneratedComplaint(
      pdfPath: file.path,
      dossierId: dossierId,
      generatedText: generatedText,
      masterHash: masterHash,
    );
  }
}
